spring:
    datasource:
        name: datasource
        url: @jdbc.url@
        username: @jdbc.username@
        password: @jdbc.password@
    aop:
        auto: true
        proxy-target-class: false
    mybatis:
        mapperLocations: classpath:/mapper/**/*Mapper.xml
        configLocation: classpath:/config/spring/mybatis-config.xml
    resources:
        static-locations: classpath:/webapp/static/
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: true
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        suffix: .ftl
        template-loader-path: classpath:/webapp/views/
        order: v4.3.0
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true

    # REDIS (RedisProperties)
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: localhost
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        pool:
            # 连接池中的最大空闲连接
            max: 8
            # 连接池中的最小空闲连接
            min: 0
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
        # 连接超时时间（毫秒）
        timeout: 0
multipart:
    # File size limit
    maxFileSize: 100Mb
    # Total request size for a multipart/form-data
    maxRequestSize: 100Mb

# 日志配置
logging:
    level:
        root: @log.level.root@

# 自定义属性配置
custom:
    # 静态资源
    static:
        # 开启合并压缩
        minify: @static.minify@
    # 跨域配置
    cors:
        # 允许的跨域来源
        allowedOrigin: '*'
        # 允许的跨域请求头
        allowedHeader: '*'
        # 允许的跨域方法
        allowedMethod: '*'
    # 图片显示http地址：http://127.0.0.1:8080/
    imgShowRoot: @imgShowRoot@
    # 图片存储的服务器根目录：/usr/tomcat/webapps/
    imgServerRoot: @imgServerRoot@
    # 图片存储的相对父目录，拼接在imgServerRoot后
    imgServerParentDir: upload/
    # excel存储的相对地址，存储在工程目录下
    xlsStoreRelativePath: store/xls
    # api
    api: http://localhost:8090/